JetBrains/intellij-community

java/debugger/impl/src/com/intellij/debugger/engine/DebugProcessEvents.java, java/debugger/impl/src/com/intellij/debugger/engine/DebugProcessImpl.java, java/debugger/impl/src/com/intellij/debugger/engine/RequestHint.java, java/debugger/impl/src/com/intellij/debugger/impl/DebuggerSession.java
This patch adds the necessary plumbing to allow a language plugin to set the step size when debugging a jvm process.
This is useful, for example, for a bytecode-oriented language, where using a step size of StepRequest.STEP_MIN makes more sense than StepRequest.STEP_LINE
=> Add support for specifying the debugging step size

plugins/tasks/tasks-core/src/com/intellij/tasks/redmine/RedmineRepository.java, plugins/tasks/tasks-core/src/com/intellij/tasks/redmine/RedmineRepositoryEditor.java
Add "assigned me" checkbox.
If this check box is not selected, the all tasks are displayed.
=> fix IDEA-132015

plugins/java-decompiler/engine/src/org/jetbrains/java/decompiler/modules/renamer/ConverterHelper.java, plugins/java-decompiler/engine/src/org/jetbrains/java/decompiler/struct/consts/ConstantPool.java
This commit makes fernflowers default renamer rename classes that have a name that is reserved by the windows namespace. See [https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#naming_conventions](url) for more information on names reserved by the windows namespace. There are currently obfuscators that take advantage of the fact that classes with these names cannot be extracted from a jar. An example of one such obfuscator is Allatori [http://www.allatori.com/doc.html#property-classes-naming](url).
I have previously signed the CLA.
=> [Fernflower] Make the default renamer rename classes that have a name that is reserved by the windows namespace

platform/util/testSrc/com/intellij/util/text/EditDistanceTest.java, spellchecker/src/com/intellij/spellchecker/engine/BaseSpellChecker.java
Word distance algorithm changed to Damerau-Levenshtein
https://en.wikipedia.org/wiki/Levenshtein_distance
https://en.wikipedia.org/wiki/Damerau–Levenshtein_distance
motivation: transposition error is really common
For example: versoin (Typo:Change to...).
expected: version. 
actual: vermin, vernon ...
=> spell checker: levenshtein->damerau-levenstein

plugins/groovy/groovy-psi/src/org/jetbrains/plugins/groovy/codeInspection/assignment/GroovyResultOfAssignmentUsedInspection.java, plugins/groovy/groovy-psi/src/org/jetbrains/plugins/groovy/lang/psi/util/PsiUtil.java, plugins/groovy/test/org/jetbrains/plugins/groovy/lang/highlighting/GrInspectionTest.groovy, plugins/groovy/test/org/jetbrains/plugins/groovy/lang/highlighting/GrResultOfAssignmentUsedTest.groovy, plugins/groovy/test/org/jetbrains/plugins/groovy/lang/highlighting/GrUnusedDefTest.groovy, plugins/groovy/testdata/highlighting/ResultOfAssignmentUsed.groovy, plugins/groovy/testdata/highlighting/UnusedDefsForArgs.groovy, plugins/groovy/testdata/highlighting/UnusedInc.groovy
Feel free to check the examples in the provided tests, e.g. https://github.com/paplorinc/intellij-community/blob/ResultOfAssignmentUsed/plugins/groovy/test/org/jetbrains/plugins/groovy/lang/highlighting/GrResultOfAssignmentUsedTest.groovy
=> Fixed `ResultOfAssignmentUsed` inspection, when it's not in method

platform/platform-impl/src/com/intellij/openapi/vfs/impl/local/NativeFileWatcherImpl.java
Some file systems aren't 100% accurate in their VFS events,
causing missed events. For instance, consider for a single file:
CHANGE - DELETE - CREATE - CHANGE
If the create is missed, then the file won't be updated because
it looks like a repetition.
This allows implementors for those file systems to override this
and get the CHANGE event.
=> Make NativeFileWatcherImpl#isRepetition protected.

platform/platform-impl/src/com/intellij/openapi/vfs/impl/local/FileWatcher.java
Previously, if these were met:
* You have more than one file watcher, and
* One of the file watchers have unwatchable roots, and
* Some other file watcher can watch everything
You would get spurious "Cannot be watched" notifications
and manual watch roots from the system.
=> Fix incorrect manual watch root calculations.

python/helpers/pydev/_pydevd_bundle/pydevd_xml.py, python/pydevSrc/com/jetbrains/python/debugger/PyDebugValue.java, python/pydevSrc/com/jetbrains/python/debugger/PyFrameAccessor.java, python/pydevSrc/com/jetbrains/python/debugger/PyReferringObjectsValue.java, python/pydevSrc/com/jetbrains/python/debugger/pydev/GetFrameCommand.java, python/pydevSrc/com/jetbrains/python/debugger/pydev/GetVariableCommand.java, python/pydevSrc/com/jetbrains/python/debugger/pydev/ProtocolParser.java, python/src/com/jetbrains/python/console/PydevConsoleCommunication.java, python/src/com/jetbrains/python/debugger/PyDebugProcess.java, python/src/com/jetbrains/python/debugger/PyDebuggerEvaluator.java, python/src/com/jetbrains/python/debugger/array/AsyncArrayTableModel.java, python/src/com/jetbrains/python/debugger/array/NumpyArrayTable.java
--Fixed issue with jump to type not working unless type is imported directly in the scope. Usually the type won't be imported in the scope, so it wasn't working in the common case
--Added support for jump to type, jump to source for frames other than the topmost frame
--Fixed issue with jump to source not working if the element is a module name
=> Fixed issues with Jump to source/ Jump to Type in python debugger

python/python-community-configure/src/com/jetbrains/python/configuration/PythonSdkDetailsDialog.java, python/src/com/jetbrains/python/testing/VFSTestFrameworkListener.java
Details:
One issue is refreshing the sdk in details dialog invokes PySdkUpdater, which in turn invalidates the modificator. the dialog tries to then use the invated modificator causing an assertion error and an NPE.
Issue two is framewok updater waits for process output on UI thread causing a major lockup
=> Minor pycharm fixes

plugins/maven/src/main/java/org/jetbrains/idea/maven/dom/MavenDomUtil.java
Comment out checking maven settings by file name. 
This check prevents navigation to maven profile defined in file with name differs from "settings.xml".
Mentioned navigation usually very helpful from Maven Projects tool window by pressing F4 key on corresponding profile.
=> Comment out checking maven settings by file name

jps/model-api/src/org/jetbrains/jps/model/ex/JpsElementChildRoleBase.java
I was playing with MAT on IDEA and found 2500+ instance of this class (subclasses included).
and there're 600+ instance of String "collection of library root".
So intern() should make sense here.
Null check is not performed as it seems not necessary :-)
=> avoid duplicate String instances of JpsElementChildRoleBase.myDebugName

python/helpers/pycharm/pytest_teamcity.py
This change fixes an issue where the PyCharm pytest runner did not report the number of tests to the test runner, resulting in a progress bar stuck at 50%.
https://youtrack.jetbrains.com/issue/PY-19541
=> PY-19541: Fix test runner progress for py.test

platform/lang-impl/src/com/intellij/codeInsight/template/postfix/templates/PostfixLiveTemplate.java
It's necessary change to properly implement postfix templates for Kotlin, at the same time preserving original file is required by `PsiFile` contract
=> Preserve original file when performing copy for postfix template

python/helpers/pycharm/django_test_manage.py
I'm developing a reusable Django app which has settings in `example_project.settings`. The `example_project` provides a project which is both a bare-bones example, and a bootstrap for the tests.
However – and perhaps unsurprisingly – another Django app also contained an `example_project`. Moreover, my project directories entry on `sys.path` only appears towards the end of the list, after many dependencies. In my case, the result was that the incorrect settings file would be imported.
I don't think this change should have any negative consequences, but I'm very much open for input.
PS. I couldn't see an email address to send the CLA to
=> Ensuring project directory is given priority prior to settings import

platform/platform-impl/src/com/intellij/ide/actions/ShowFilePathAction.java
Update appName pattern to match xdg-mime output of Debian 8 which is `org.gnome.Nautilus.desktop`
Fixes https://youtrack.jetbrains.com/issue/IDEA-162050
=> Update appName pattern

python/helpers/pydev/_pydevd_bundle/pydevd_vars.py
PY-20771: Min and max values for columns 100 and above were computed incorrectly sometimes causing exceptions during rendering.
The UI exceptions are also one of the reasons for poor performance
=> PY-20771: Fix dataframe rendering issue in frames 100+ columns

plugins/gradle/tooling-extension-impl/src/org/jetbrains/plugins/gradle/tooling/internal/ExtraModelBuilder.java, plugins/gradle/tooling-extension-impl/src/org/jetbrains/plugins/gradle/tooling/internal/init/init.gradle
This fixes a memory leak inside the Gradle daemon caused by Idea Gradle plugin.
Here's a description of the memory leak:
The custom classloader created by `ijinit.gradle` was not garbage collected and it was keeping references to a lot of object instances. The instances were held in the static `ExtraModelBuilder.buildersLoader` field. This field referenced an instance of `ExternalProjectBuilderImpl` which has a `cache` field with a lot of instances. 
Each new call using the same Gradle daemon instance would leak more memory.
=> Fix memory leak inside the Gradle daemon caused by Idea Gradle plugin

java/java-runtime/src/com/intellij/rt/ant/execution/IdeaAntLogger2.java
myTaskPriority needs to be set to verbose in order to be able to turn it off by AntBuildFileImpl.VERBOSE.set(editPropertyContainer, false);
Signed-off-by: Martin Zdarsky-Jones zdary@zdary.cz
=> IDEA-162949 myTaskPriority set to verbosive

xml/relaxng/src/org/intellij/plugins/relaxNG/compact/lexer/SimpleCharStream.java
… to constructors with the same parameters, instead of the literal value 4096.
@Eugene-Kudelevsky: This follows commit 7f86ba0.
=> Pass otherwise unused buffersize parameters

plugins/maven/maven3-server-common/src/org/jetbrains/idea/maven/server/embedder/FieldAccessor.java, plugins/maven/maven3-server-impl/src/org/jetbrains/idea/maven/server/Maven3ServerEmbedderImpl.java, plugins/maven/maven30-server-impl/src/org/jetbrains/idea/maven/server/Maven30ServerEmbedderImpl.java
The first commit replaces uses of the method, which is all we apparently need at the moment to compile with JDK 9. The second commit removes the method—separate because I'm not sure if it needs to be kept in case of uses outside the project.
=> Address FieldAccessor.get compilation failure in JDK 9

plugins/github/src/org/jetbrains/plugins/github/GithubCreatePullRequestWorker.java, plugins/github/src/org/jetbrains/plugins/github/util/GithubUtil.java, plugins/github/test/org/jetbrains/plugins/github/GithubUtilTest.java
When you create PR now the title is the first line of commit message and description is another text.
It's the same behaviour that used when you create PR from Github website or using hub (Github CLI tools)
=> Fill subject and description in Github Pull Request creation dialog

plugins/gradle/tooling-extension-impl/src/org/jetbrains/plugins/gradle/tooling/util/DependencyResolverImpl.groovy
The gradle import resolves source and javadoc JAR files for all artifacts, including project dependency artifacts. These artifacts do not exist in external repositories and so gradle makes many unsuccessful HTTP calls to pom files as well as source and javadoc JARs across all configured repositories every time the project is imported. For large multi-module projects with many external repositories these unsuccessful HTTP calls can take a long time, on the order of many minutes.
This fix limits the resolved artifacts to those from external dependencies. I have checked that all tests in gradle-tooling-extension-impl still pass.
=> IDEA-165738 Gradle import is very slow in multi-module projects

plugins/gradle/src/org/jetbrains/plugins/gradle/execution/test/runner/GradleTestsExecutionConsoleManager.java, plugins/gradle/src/org/jetbrains/plugins/gradle/execution/test/runner/GradleTestsExecutionConsoleOutputProcessor.java, plugins/gradle/src/org/jetbrains/plugins/gradle/execution/test/runner/events/AbstractTestEvent.java, plugins/gradle/src/org/jetbrains/plugins/gradle/execution/test/runner/events/AfterSuiteEvent.java, plugins/gradle/src/org/jetbrains/plugins/gradle/execution/test/runner/events/AfterTestEvent.java, plugins/gradle/src/org/jetbrains/plugins/gradle/execution/test/runner/events/BeforeSuiteEvent.java, plugins/gradle/src/org/jetbrains/plugins/gradle/execution/test/runner/events/BeforeTestEvent.java, plugins/gradle/src/org/jetbrains/plugins/gradle/execution/test/runner/events/ConfigurationErrorEvent.java, plugins/gradle/src/org/jetbrains/plugins/gradle/execution/test/runner/events/OnOutputEvent.java, plugins/gradle/src/org/jetbrains/plugins/gradle/execution/test/runner/events/ReportLocationEvent.java, plugins/gradle/src/org/jetbrains/plugins/gradle/execution/test/runner/events/TestEvent.java, plugins/gradle/src/org/jetbrains/plugins/gradle/execution/test/runner/events/TestEventXPPXmlView.java, plugins/gradle/src/org/jetbrains/plugins/gradle/execution/test/runner/events/TestEventXmlView.java, plugins/gradle/src/org/jetbrains/plugins/gradle/execution/test/runner/events/TestEventXmlXPathView.java, plugins/gradle/src/org/jetbrains/plugins/gradle/execution/test/runner/events/XmlXpathHelper.java, plugins/gradle/src/org/jetbrains/plugins/gradle/util/XmlXpathHelper.java, plugins/gradle/testSources/org/jetbrains/plugins/gradle/execution/TestEventXPPXmlViewTest.java, plugins/gradle/testSources/org/jetbrains/plugins/gradle/execution/TestEventXmlViewTestCase.java, plugins/gradle/testSources/org/jetbrains/plugins/gradle/execution/TestEventXmlXPathViewTest.java
As discussed in the https://youtrack.jetbrains.com/issue/IDEA-167449 issue I decided to implement faster XML processing for Gradle plugin that would avoid my most pain point for tests with heavy output flow. 
Before the fix, IDEA UI was too overloaded. According to Activity Monitor IDEA process was eating even more CPU than tests worker process. You may find snapshot in the issue. 
After the fix I see It consumes less CPU wither by IDEA UI responsiveness or by fresh CPU profiling.
Current implementation I use XStreams (it was included in classpath) Hierarchical parser that uses KXML pull parser implementation. The whole processing is done within one class.
Unfortunately, I was not able to implement integration tests to measure performance boost more technically as well as to make sure …
=> Speedup gradle test output XML processing

platform/external-system-api/src/com/intellij/openapi/externalSystem/model/execution/ExternalSystemTaskExecutionSettings.java, platform/external-system-impl/src/com/intellij/openapi/externalSystem/service/execution/ExternalSystemRunConfiguration.java, plugins/gradle/src/org/jetbrains/plugins/gradle/service/project/BaseGradleProjectResolverExtension.java
Provide a way for executors other than the debugging executor to set VM parameters that are patched into the gradle Java task. This is solved with a special key that can be set in the user data of the ExecutionEnvironment.
=> IDEA-165963 Gradle run configurations cannot be profiled

python/src/com/jetbrains/python/console/PydevConsoleRunnerFactory.java
Changed return type to PydevConsoleRunner to add ability to extend this factory with returning your own PydevConsoleRunner that just implements the interface but not extends PydevConsoleRunnerImpl.
=> Change return type of PydevConsoleRunnerFactory

java/java-tests/testSrc/com/intellij/psi/formatter/java/JavaEnterActionTest.java, platform/lang-impl/src/com/intellij/formatting/engine/IndentAdjuster.java
Reuse indentation from previous block when alignment is present (IDEA-173208)
Previous version didn't consider child attributes for indentation during
reconstruction from parent.
#IDEA-173208 Fixed
=> Fix new line indent when alignment is enabled (IDEA-173208)

plugins/gradle/src/org/jetbrains/plugins/gradle/action/PasteMvnDependencyPreProcessor.java, plugins/gradle/testSources/org/jetbrains/plugins/gradle/codeInsight/actions/MvnDependencyPasteTest.java
Gradle supports maven classifiers https://docs.gradle.org/current/userguide/dependency_management.html#sub:classifiers. This change adds support for classifiers in `PasteMvnDependencyPreProcessor`. 
I've signed CLA.
=> Pasting mvn dependency with classifier to gradle

java/java-impl/src/com/intellij/psi/impl/source/codeStyle/javadoc/JDClassComment.java, java/java-impl/src/com/intellij/psi/impl/source/codeStyle/javadoc/JDComment.java, java/java-impl/src/com/intellij/psi/impl/source/codeStyle/javadoc/JDMethodComment.java, java/java-impl/src/com/intellij/psi/impl/source/codeStyle/javadoc/JDParamListOwnerComment.java, java/java-impl/src/com/intellij/psi/impl/source/codeStyle/javadoc/JDParser.java, java/java-impl/src/com/intellij/psi/impl/source/codeStyle/javadoc/JDTag.java
Fixes a couple issues along the way,
- Disabling "Preserve Line Feeds" has no affect on the JavaDoc description unless a line already exceeds the right margin. This is inconsistent with how tag blocks are handled (they are generally re-flowed regardless of if the right margin has been exceeded).
- A couple class-level tags (@author and @version) used inconsistent continuation indentation from other tags.
This was prep-work for another MR to fix [IDEA-23188](https://youtrack.jetbrains.com/issue/IDEA-23188)
=> JavaDoc formatting refactor.

java/java-impl/src/com/intellij/application/options/JavaDocFormattingPanel.java, java/java-impl/src/com/intellij/psi/impl/source/codeStyle/javadoc/JDClassComment.java, java/java-impl/src/com/intellij/psi/impl/source/codeStyle/javadoc/JDComment.java, java/java-impl/src/com/intellij/psi/impl/source/codeStyle/javadoc/JDMethodComment.java, java/java-impl/src/com/intellij/psi/impl/source/codeStyle/javadoc/JDParamListOwnerComment.java, java/java-impl/src/com/intellij/psi/impl/source/codeStyle/javadoc/JDParser.java, java/java-impl/src/com/intellij/psi/impl/source/codeStyle/javadoc/JDTag.java, platform/lang-api/src/com/intellij/psi/codeStyle/CodeStyleSettings.java, platform/platform-resources-en/src/messages/ApplicationBundle.properties
This fixes https://youtrack.jetbrains.com/issue/IDEA-23188
This change is based on #526 so the first commit can be ignored.
=> Add option for JavaDoc continuation indent.

plugins/java-decompiler/engine/README.md
The globbing characters are treated as bullet points by GFM.
=> README.md: escape * and +

plugins/gradle/src/org/jetbrains/plugins/gradle/service/execution/GradleExecutionHelper.java, plugins/gradle/testSources/org/jetbrains/plugins/gradle/service/execution/GradleExecutionHelperTest.java
The GradleExecutionHelper was previously logging android keystore passwords.  This change will obfuscate the values of a parameter ending in '.password' within the `idea.log` file.
=> Avoid logging passwords in GradleExecutionHelper

platform/external-system-api/src/com/intellij/openapi/externalSystem/model/project/ModuleData.java, platform/external-system-impl/src/com/intellij/openapi/externalSystem/service/project/manage/AbstractModuleDataService.java, plugins/gradle/src/org/jetbrains/plugins/gradle/service/project/BaseGradleProjectResolverExtension.java, plugins/gradle/testSources/org/jetbrains/plugins/gradle/importing/GradleMiscImportingTest.java
In
https://github.com/gradle/gradle/commit/8e02bc268f6478773ca6daf49bea9aed14c5d1eb
support for this property was added to the Gradle tooling API, now
it can be used for the Gradle import in IDEA in order to correctly
select the JDK that was configured by the user in the gradle project.
This is important for projects that have modules with different
language levels.
=> IDEA-154288 - Gradle import: Support jdkName property in IdeaModule

plugins/java-decompiler/engine/src/org/jetbrains/java/decompiler/modules/renamer/ConverterHelper.java
RESERVED_WINDOWS_NAMESPACE contains duplicate entries of `aux` and doesn't contain `con` which is reserved name too.
=> Duplicate entries in RESERVED_WINDOWS_NAMESPACE and absense of `con`

plugins/java-decompiler/engine/src/org/jetbrains/java/decompiler/modules/renamer/ConverterHelper.java
An obfuscated application I'm reversing has a class called "OoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO" in it (256 characters long). This decompiles fine into a JAR, but if I want to unpack the JAR in order to refactor code and/or recompile it, I quickly run in to filesystem filename length limits ([almost all filesystems](https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits) top out at 255 characters).
This patch renames classes that would exceed 255 characters in length once ".class" is added to the name.
=> FernFlower: Rename classes whose filenames will exceed 255 characters

platform/platform-api/src/com/intellij/openapi/ui/DialogWrapper.java
If the error label in the DialogWrapper is displayed on multiple lines,
any update of the error message that keeps it on several lines will
cause the dialog window to shrink.
=> Fix bug in resizing of DialogWrapper with large error label

plugins/java-decompiler/engine/src/org/jetbrains/java/decompiler/modules/renamer/ConverterHelper.java, plugins/java-decompiler/engine/test/org/jetbrains/java/decompiler/ConverterHelperTest.java
This patch propose following improvements to the default renaming functionality:
1. All identifiers should be compliant to the JLS9 section 3.8 and SHOULD NOT contains so-called "ignorable" characters.
Ignorable characters are silently removed by javac during the compilation and thus may appear only in specially crafted obfuscated classes.
For more information about "ignorable" characters see <a href="https://bugs.openjdk.java.net/browse/JDK-7144981">JDK-7144981</a>.
2. Add dedicated unit tests for `org.jetbrains.java.decompiler.modules.renamer.ConverterHelper` class.
=> Improve malformed identifiers handling in `-ren=1` mode

python/psi-api/src/com/jetbrains/python/psi/types/TypeEvalContext.java, python/psi-api/src/com/jetbrains/python/psi/types/TypeEvalContextBasedCache.java
The problem here is that while the map holding cached values is softly referenced , the values themselves are not. This means the GC can either collect the entire map or none of it. Since the collector uses an LRU policy to collect soft refs and the reference to the map is usually 'recently used' it does not get collected until the memory situation becomes critical.  This becomes a problem when running inspections in batch mode on a large enough workload. 
This patch makes the cached values themselves softly referenced so that the gc can collect TypeEvalContext instances that have no been recently used.
=> Let unused TypeEvalContext instances be gc-ed

platform/platform-resources/src/launcher.py
It's a common pattern for power users to replace `open` with some other
file manager. Since the launcher relies on the OS `open` command, having
the full path will avoid issues with users aliasing `open` to something
else while keeping the current behavior the same.
=> Fix path for open command in launcher

platform/platform-resources/src/launcher.py
sys.version_info does not return a named tuple until Python 2.7
=> [platform] Support Python 2.6 in python launcher

platform/build-scripts/groovy/org/jetbrains/intellij/build/impl/TestingTasksImpl.groovy, platform/build-scripts/groovy/org/jetbrains/intellij/build/impl/VmOptionsGenerator.groovy, platform/testGuiFramework/src/com/intellij/testGuiFramework/launcher/GuiTestLocalLauncher.kt
This CL still keeps the canonicalization prefix cache disabled since
that is known to have consistency issues.
The canonicalization cache helps to address performance issues on the
Windows platform where the File.getCanonicalPath is significantly slower
than in other platforms.
As per my conversation with @trespasserw, this was disabled back in Apple JDK6 since it didn't handle correctly symlinks and kept re-indexing parts of the JDK. I've tested this locally and it seems to work correctly now.
=> Re-enable canonicalization cache

platform/util/src/com/intellij/openapi/util/SystemInfo.java
Android Studio (and the Android plugin) would benefit from having the detection done in platform code.
=> Recognize Chrome OS in SystemInfo

plugins/java-decompiler/engine/src/org/jetbrains/java/decompiler/util/TextUtil.java
The current code recognizes `enum` as keyword on versions **greater than 5**. However, enums and the keyword have been introduced in Java 5. This PR simply changes the check to check whether a given version is **greater than or equal to 5**.
=> decompiler: Recognize enum as keyword on Java 5

platform/platform-impl/src/com/intellij/ide/ui/laf/darcula/DarculaTableHeaderUI.java
Otherwise the last column looks wider than it actually is when a table's
auto resize mode is set to AUTO_RESIZE_OFF
=> Use the total column width instead of the component width

platform/platform-impl/src/com/intellij/openapi/actionSystem/impl/ActionPopupMenuImpl.java
In the issue reported at IDEA-242047, context menu on macOS does not show with error because of failing on finding location/index of Mnemonic character, which is already stripped by the change introduced in https://github.com/JetBrains/intellij-community/commit/d14e2d658b6a295cd53e2d72ee49204a7ebe491f, while Mnemonic handling should not be done on macOS.
To avoid/fix this error, necessity of Mnemonic handling should be determined by calling "UISettings.getInstance().getDisableMnemonics()" like done in other places.
=> Disable Mnemonics check for context menu on macOS

xml/impl/src/com/intellij/xml/actions/GenerateXmlTagAction.java
don't add abstract elements to required sub tags list when generating xml elements
=> IDEA-290774 don't add abstract elements to xml

plugins/kotlin/code-insight/inspections-shared/src/org/jetbrains/kotlin/idea/codeInsight/inspections/shared/DelegationToVarPropertyInspection.kt, plugins/kotlin/code-insight/inspections-shared/tests/k1/test/org/jetbrains/kotlin/idea/codeInsight/inspections/shared/SharedK1LocalInspectionTestGenerated.java, plugins/kotlin/code-insight/inspections-shared/tests/k2/test/org/jetbrains/kotlin/idea/k2/codeInsight/inspections/shared/SharedK2LocalInspectionTestGenerated.java, plugins/kotlin/code-insight/inspections-shared/tests/testData/inspectionsLocal/delegationToVarProperty/usedForOtherClass.kt, plugins/kotlin/code-insight/inspections-shared/tests/testData/inspectionsLocal/delegationToVarProperty/usedInFunction.kt
https://youtrack.jetbrains.com/issue/KTIJ-24692
=> KTIJ-24692 Delegating to 'var' property: "Remove var" quick fix produces incompilable code if property belongs to outer class

platform/core-api/src/com/intellij/psi/stubs/IStubElementType.java
Previously it queried isLazilyRegistered() before isInitialized(), leading to false-positive errors if initialization happens inbetween.
(Note that isLazilyRegistered() returns false if initialization has not happened yet.)
Issue link: https://youtrack.jetbrains.com/issue/IJPL-160566
=> Fix race in IStubElementType (IJPL-160566)
