JetBrains/intellij-community

plugins/maven/src/main/java/org/jetbrains/idea/maven/project/MavenProject.java
loads annotation processor options from bsc.maven.plugin
=> fix IDEA-128528

java/compiler/openapi/src/com/intellij/openapi/compiler/ExportableUserDataHolderBase.java, platform/platform-impl/src/com/intellij/openapi/vfs/newvfs/impl/UserDataInterner.java, platform/util/src/com/intellij/util/keyFMap/ArrayBackedFMap.java, platform/util/src/com/intellij/util/keyFMap/EmptyFMap.java, platform/util/src/com/intellij/util/keyFMap/KeyFMap.java, platform/util/src/com/intellij/util/keyFMap/MapBackedFMap.java, platform/util/src/com/intellij/util/keyFMap/OneElementFMap.java, platform/util/src/com/intellij/util/keyFMap/PairElementsFMap.java, platform/util/testSrc/com/intellij/util/keyFMap/KeyFMapTest.java
Changes in KeyFMap are needed for Kotlin
=> Add the ability to get keys and values from KeyFMap

plugins/tasks/tasks-core/src/com/intellij/tasks/trello/TrelloTask.java, plugins/tasks/tasks-core/src/com/intellij/tasks/trello/model/TrelloCard.java
https://youtrack.jetbrains.com/issue/IDEA-139903
=> IDEA-139903 TaskManagement: Trello: Change 'number' placeholder in commit message

platform/external-system-impl/src/com/intellij/openapi/externalSystem/service/project/manage/ContentRootDataService.java, platform/external-system-impl/src/com/intellij/openapi/externalSystem/service/project/manage/LibraryDependencyDataService.java
For really big projects there are too much output to idea.log
=> Debug log level for project data services

plugins/tasks/tasks-core/src/com/intellij/tasks/youtrack/YouTrackRepository.java
Contribution agreement has been signed already: https://github.com/JetBrains/intellij-community/pull/222
=> IDEA-101238 fixed url parameter encoding for youtrack time tracking

platform/built-in-server/src/org/jetbrains/io/fastCgi/FastCgiService.kt, platform/built-in-server/testSrc/BinaryRequestHandlerTest.kt, platform/configuration-store-impl/src/ExportSettingsAction.kt, platform/configuration-store-impl/src/SchemeManagerImpl.kt, platform/configuration-store-impl/testSrc/SchemeManagerTest.kt, platform/configuration-store-impl/testSrc/StorageManagerTest.kt, platform/core-api/src/org/jetbrains/concurrency/AsyncPromise.java, platform/core-api/src/org/jetbrains/concurrency/DonePromise.java, platform/core-api/src/org/jetbrains/concurrency/Promise.java, platform/core-api/src/org/jetbrains/concurrency/RejectedPromise.java, platform/script-debugger/backend/src/EvaluateContextBase.kt, platform/script-debugger/backend/src/SuspendContext.kt, platform/script-debugger/backend/src/SuspendContextManager.kt, platform/script-debugger/backend/src/SuspendContextManagerBase.kt, platform/script-debugger/debugger-ui/src/org/jetbrains/debugger/DebugProcessImpl.kt, platform/script-debugger/debugger-ui/src/org/jetbrains/debugger/VariableView.kt, platform/script-debugger/protocol/protocol-reader-runtime/src/org/jetbrains/jsonProtocol/EventMap.kt, platform/util/testSrc/com/intellij/util/xmlb/XmlSerializerTest.kt, platform/vcs-log/impl/test/com/intellij/vcs/log/data/VisiblePackBuilderTest.kt, plugins/java-decompiler/plugin/src/org/jetbrains/java/decompiler/IdeaDecompiler.kt, plugins/settings-repository/src/actions/SyncAction.kt, plugins/settings-repository/src/git/GitEx.kt, plugins/settings-repository/src/git/pull.kt, plugins/settings-repository/src/keychain/OSXKeychainLibrary.kt, plugins/settings-repository/src/settings/upstreamEditor.kt
Fix type projection usages, deprecated symbols cleanup
=> Make compilable both with latest Kotlin and beta4

plugins/java-decompiler/engine/src/org/jetbrains/java/decompiler/struct/consts/ConstantPool.java
=> [IDEA-137253] Fixed renaming class elements when decompiling

plugins/groovy/groovy-psi/resources/inspectionDescriptions/ChangeToOperator.html, plugins/groovy/groovy-psi/src/org/jetbrains/plugins/groovy/codeInspection/GroovyInspectionBundle.properties, plugins/groovy/groovy-psi/src/org/jetbrains/plugins/groovy/codeInspection/changeToOperator/ChangeToOperatorInspection.java, plugins/groovy/groovy-psi/src/org/jetbrains/plugins/groovy/codeInspection/changeToOperator/data/MethodCallData.java, plugins/groovy/groovy-psi/src/org/jetbrains/plugins/groovy/codeInspection/changeToOperator/data/OptionsData.java, plugins/groovy/groovy-psi/src/org/jetbrains/plugins/groovy/codeInspection/changeToOperator/data/ReplacementData.java, plugins/groovy/groovy-psi/src/org/jetbrains/plugins/groovy/codeInspection/changeToOperator/transformations/AsBooleanTransformation.java, plugins/groovy/groovy-psi/src/org/jetbrains/plugins/groovy/codeInspection/changeToOperator/transformations/BinaryTransformation.java, plugins/groovy/groovy-psi/src/org/jetbrains/plugins/groovy/codeInspection/changeToOperator/transformations/CallTransformation.java, plugins/groovy/groovy-psi/src/org/jetbrains/plugins/groovy/codeInspection/changeToOperator/transformations/CompareToTransformation.java, plugins/groovy/groovy-psi/src/org/jetbrains/plugins/groovy/codeInspection/changeToOperator/transformations/EqualsTransformation.java, plugins/groovy/groovy-psi/src/org/jetbrains/plugins/groovy/codeInspection/changeToOperator/transformations/GetAtTransformation.java, plugins/groovy/groovy-psi/src/org/jetbrains/plugins/groovy/codeInspection/changeToOperator/transformations/IsCaseTransformation.java, plugins/groovy/groovy-psi/src/org/jetbrains/plugins/groovy/codeInspection/changeToOperator/transformations/PutAtTransformation.java, plugins/groovy/groovy-psi/src/org/jetbrains/plugins/groovy/codeInspection/changeToOperator/transformations/Transformation.java, plugins/groovy/groovy-psi/src/org/jetbrains/plugins/groovy/codeInspection/changeToOperator/transformations/Transformations.java, plugins/groovy/groovy-psi/src/org/jetbrains/plugins/groovy/codeInspection/changeToOperator/transformations/UnaryTransformation.java, plugins/groovy/groovy-psi/src/org/jetbrains/plugins/groovy/lang/psi/impl/statements/expressions/HardcodedGroovyMethodConstants.java, plugins/groovy/groovy-psi/src/org/jetbrains/plugins/groovy/lang/psi/impl/statements/expressions/TypesUtil.java, plugins/groovy/groovy-psi/src/org/jetbrains/plugins/groovy/lang/psi/impl/utils/BoolUtils.java, plugins/groovy/groovy-psi/src/org/jetbrains/plugins/groovy/lang/psi/impl/utils/ComparisonUtils.java, plugins/groovy/src/META-INF/plugin.xml, plugins/groovy/test/org/jetbrains/plugins/groovy/inspections/GrChangeToOperatorTest.groovy
Fixes https://youtrack.jetbrains.com/issue/IDEA-95818
```
a.bitwiseNegate()       → ~a       
a.negative()            → -a       
a.positive()            → +a       
a.call()                → a()      
a.next()                → ++a      
a.previous()            → --a      
a.asBoolean()           → !!a      
!a.asBoolean()          → !a       
if (a.asBoolean())      → if (a)
if (!a.asBoolean())     → if (!a)
a.minus(b)              → a - b    
a.plus(b)               → a + b    
a.power(b)              → a**b     
a.div(b)                → a / b    
a.mod(b)                → a % b    
a.or(b)                 → a | b    
a.and(b)                → a & b    
a.xor(b)                → a ^ b    
a.leftShift(b)          → a << b   
a.rightShift(b)         → a >> b   
a.rightShiftUnsigned(b) → …
```
=> Added `Convert to Operator` Groovy inspection

platform/lang-impl/src/com/intellij/ide/fileTemplates/impl/FileTemplateManagerImpl.java, resources-en/src/fileTemplates/default.html, resources-en/src/fileTemplates/includes/File Header.java.html, resources-en/src/fileTemplates/includes/default.html
I was looking to add the FILE_PATH variable too, but can't find how to do it.
=> IDEA-137640: New FileTemplate time variables

java/java-analysis-impl/src/com/intellij/codeInspection/dataFlow/HardcodedContracts.java, java/java-tests/testData/inspection/dataFlow/fixture/AssumeThat.java, java/java-tests/testData/inspection/dataFlow/fixture/GoogleTruth.java, java/java-tests/testSrc/com/intellij/codeInspection/DataFlowInspectionTest.java
… just like existing contracts for assert methods.
https://youtrack.jetbrains.com/issue/IDEA-158732
=> Apply hard-coded contracts to assume methods

python/helpers/pycharm/tcunittest.py
https://youtrack.jetbrains.com/issue/PY-15166
=> PY-15166 Fixed subtest location marks for correct display in tree.

java/java-runtime/src/com/intellij/rt/ant/execution/IdeaAntLogger2.java
when exception is thrown in try block it'll get logged as verbosive message
Signed-off-by: Martin Zdarsky-Jones zdary@zdary.cz
=> IDEA-141243 added support for ant-contrib try/catch-task

plugins/ant/src/com/intellij/lang/ant/config/execution/AntCommandLineBuilder.java
Signed-off-by: Martin Zdarsky-Jones zdary@zdary.cz
=> IDEA-163243 fixed confussion in parameter names

platform/testFramework/src/com/intellij/mock/MockModule.java
Used by Android Plugin tests (as of Android Studio 2.3)
=> Add ability to provide name on MockModule for testing

plugins/terminal/src/org/jetbrains/plugins/terminal/LocalTerminalCustomizer.java, plugins/terminal/src/org/jetbrains/plugins/terminal/LocalTerminalDirectRunner.java, plugins/terminal/src/org/jetbrains/plugins/terminal/TerminalProjectOptionsProvider.kt, python/python-terminal/src/com/jetbrains/python/sdk/PyVirtualEnvTerminalCustomizer.kt
This is something we want to be able to do in our internal Google plugin. Thanks!
=> Pass the project as a parameter to getDefaultFolder.

plugins/java-decompiler/engine/README.md
This PR rewrites the fernflower README file in markdown format. And that's all. :)
=> Rewrite fernflower README with markdown

platform/util/src/com/intellij/openapi/util/SystemInfo.java
See https://fedoraproject.org/wiki/How_to_debug_Wayland_problems
=> Recognize Wayland sessions in SystemInfo

uast/uast-common/src/org/jetbrains/uast/UastContext.kt, uast/uast-common/src/org/jetbrains/uast/declarations/UMethod.kt, uast/uast-common/src/org/jetbrains/uast/declarations/UVariable.kt, uast/uast-common/src/org/jetbrains/uast/expressions/ULambdaExpression.kt, uast/uast-java/src/org/jetbrains/uast/java/expressions/JavaULambdaExpression.kt, uast/uast-tests/java/Simple/FunctionalInterfaceType.java, uast/uast-tests/java/Simple/VariableAnnotation.java, uast/uast-tests/java/Simple/VariableAnnotation.log.txt, uast/uast-tests/java/Simple/VariableAnnotation.render.txt, uast/uast-tests/test/org/jetbrains/uast/test/java/JavaUastApiTest.kt, uast/uast-tests/test/org/jetbrains/uast/test/java/SimpleJavaRenderLogTest.kt
Fix for https://github.com/JetBrains/uast/issues/16
=> Minor UAST improvements

platform/external-system-impl/src/com/intellij/openapi/externalSystem/service/internal/ExternalSystemExecuteTaskTask.java, plugins/gradle/src/org/jetbrains/plugins/gradle/execution/test/runner/TestClassGradleConfigurationProducer.java, plugins/gradle/src/org/jetbrains/plugins/gradle/execution/test/runner/TestMethodGradleConfigurationProducer.java, plugins/gradle/src/org/jetbrains/plugins/gradle/service/execution/GradleExecutionHelper.java
Nested classes should be qualified with $
Fix passing test selector with $ to Gradle tooling API
=> Fix nested test classes run in delegate to Gradle mode

platform/build-scripts/resources/linux/scripts/executable-template.sh
see https://wiki.ubuntu.com/DashAsBinSh#echo
=> Replace echo with printf to interpret \n as newline

java/java-analysis-impl/src/com/intellij/codeInspection/dataFlow/fix/RedundantInstanceofFix.java, java/java-tests/testData/codeInsight/daemonCodeAnalyzer/quickFix/redundantInstanceOf/afterInstanceOfNegated.java, java/java-tests/testData/codeInsight/daemonCodeAnalyzer/quickFix/redundantInstanceOf/beforeInstanceOfNegated.java
Because up/down keys are painful to use on some laptops
=> Respect configured up/down user keys in tree views

updater/src/ie/wombat/jbdiff/JBDiff.java
Previously, on large-ish files, JBDiff#split would sometimes cause
StackOverflowExceptions due to the use of tail recursion. Changed to
use stacks to maintain state during iteration, and eliminated the
recursion.
Also updating variable names to be more readable.
(cherry picked from commit 59aee5d)
=> Eliminating tail recursion in JBDiff#split

platform/platform-impl/src/com/intellij/ide/ui/laf/intellij/WinIntelliJComboBoxUI.java, platform/util/src/com/intellij/util/ui/components/BorderLayoutPanel.java
This addresses a regression introduced by change 54c98acf.
See comment in code for description of the fix.
=> IDEA-193617 Fix a11y of combo boxes

plugins/kotlin/gradle/gradle-java/src/org/jetbrains/kotlin/idea/gradleJava/KotlinJavaMPPSourceSetDataService.kt
=> Fix KotlinJavaMPPSourceSetDataService.isTestModuleById performance

platform/platform-impl/src/com/intellij/openapi/vfs/impl/local/LocalFileSystemBase.java
In case-insensitive filesystems, canonizing a given name to the one in the filesystem is expensive if we need to enumerate directories. Attempt to compute an answer earlier by generating a full realpath, which should succeed in the absence of symbolic links.
=> Attempt to short-circuit directory enumeration
